# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default='descripcion generica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(default='actividades/silueta.png', upload_to='actividades'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
