# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20170422_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.Lugar'),
            preserve_default=False,
        ),
    ]
